name: 'URL Shortener'
author: 'emcee21'
description: 'Shorten URLs using an API'

inputs:
  api-url:
    description: 'API endpoint URL'
    required: true
    default: 'https://clk.wnml.io/api/v2'
  api-key:
    description: 'API key'
    required: true
  target-url:
    description: 'URL to shorten'
    required: true
  domain:
    description: 'Domain'
    required: false
    default: 'clk.wnml.net'
  description:
    description: 'Description'
    required: false
  expire-in:
    description: 'Expiration time'
    required: false
  reuse:
    description: 'Reuse'
    required: false
    default: 'false'
  timeout:
    description: 'Timeout'
    required: false
    default: '60'

outputs:
  link:
    description: 'The shortened URL'
  id:
    description: 'The ID of the shortened URL'

runs:
  using: 'node20'
  main: 'dist/index.js'
