name: Cut

on:
  workflow_dispatch:
    inputs:
      target-url:
        required: true
        description: 'The URL to shorten'

env:
  KUTT_API_URL: ${{ vars.KUTT_API_URL || 'https://kutt.it/api/v2' }}
  KUTT_API_KEY: ${{ secrets.KUTT_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Shorten URL
        id: shorten
        uses: ./
        with:
          api-url: ${{ vars.KUTT_API_URL || 'https://kutt.it/api/v2' }}
          api-key: ${{ secrets.KUTT_API_KEY }}
          target-url: ${{ inputs.target-url }}

      - name: Display shortened URL
        run: |
          echo "Shortened URL: ${{ steps.shorten.outputs.link }}"
          echo "Link ID: ${{ steps.shorten.outputs.id }}"
